# Use root/mysql as user/password credentials
version: '3.1'

services:
  db:
    container_name: mydb
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql 
    ports:
      - 3306:3306
    networks:
      - my-bridge
    build:
      dockerfile: Dockerfile.db
    volumes: 
     - ./dbdata:/var/lib/mysql
  php-apache:
    container_name: myphp
    image: php:8.2
    restart: always
    ports:
      - 80:80
    networks:
      - my-bridge
    build: 
      dockerfile: Dockerfile.php
    volumes:
      - ./:/var/www/html
      - ./null:/var/www/html/dbdata
networks:
 my-bridge:
  name: mybridge
volumes:
 dbdata:
   name: mydata